# Stocks must be Yahoo Finance tickers; ".NS" denotes NSE listings.
stocks:
  - HDFCBANK.NS
  - RELIANCE.NS
  - INFY.NS
  - TCS.NS
  - ICICIBANK.NS

data:
  lookback_months: 12
  interval: 1d           # 1m, 5m, 1h also allowed; beware API limits.

strategy:
  rsi_period: 14
  fast_ma: 20
  slow_ma: 50
  buy_rsi: 30
  sell_rsi: 70

backtest:
  initial_cash: 1_000_0   # INR
  commission: 0.0005        # 0.05%

google_sheets:
  creds_json: "./htohkey.json"
  spreadsheet_name: "algo-trading-logs"

telegram:
  enabled: true
  bot_token: "bot_token"
  chat_id: "chat_id"

logging:
  level: "INFO" 